[theme]
base = "dark"
primaryColor = "#FFD400"
backgroundColor = "#06080C"
secondaryBackgroundColor = "#10141B"
textColor = "#F7F8FA"
font = "sans serif"

[client]
toolbarMode = "minimal"
showErrorDetails = "full"

[server]
headless = true
